# Generated by Django 5.1.7 on 2025-03-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reactions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
