# Generated by Django 5.1.7 on 2025-05-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_public_id_alter_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='public_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
