# Generated by Django 5.1.7 on 2025-04-04 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_attachment_url_chatmessage_reactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('chat', 'sender', 'content', 'message_type', 'timestamp')},
        ),
    ]
