# Generated by Django 5.1.7 on 2025-04-26 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_attachment_mime_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', '-timestamp'], name='chat_chatme_chat_id_92277f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='chat_chatme_sender__3a9411_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_deleted'], name='chat_chatme_is_dele_299637_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_group'], name='chat_chatro_is_grou_309231_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['-updated_at'], name='chat_chatro_updated_fe8347_idx'),
        ),
    ]
