# Generated by Django 5.1.7 on 2025-04-30 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='read_by',
            field=models.ManyToManyField(related_name='read_group_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
