# Generated by Django 5.1.7 on 2025-05-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='attachment_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
