# Generated by Django 5.1.7 on 2025-05-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmessage_attachment_mime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='attachment_mime_type',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
