# Generated by Django 5.1.7 on 2025-05-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmessage_reactions_groupmessage_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='group_profiles/'),
        ),
    ]
