# Generated by Django 5.1.7 on 2025-05-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_groupmessage_attachment_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='can_members_send_messages',
            field=models.BooleanField(default=True),
        ),
    ]
