# Generated by Django 5.1.7 on 2025-05-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_can_members_send_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='can_members_send_messages',
        ),
    ]
