# Generated by Django 5.1.7 on 2025-05-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_can_members_send_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='can_members_send_messages',
            field=models.BooleanField(default=True),
        ),
    ]
