# Generated by Django 5.1.7 on 2025-05-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_groupmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='groups.groupmessage'),
        ),
    ]
